# .bashrc

# Exports
export PS1="\\u@\h \\W]\\$ "
export EDITOR=vi
export HISTFILESIZE=3000
export HISTCONTROL=ignoredups

# Global aliases
alias rm='rm -I' # warn if removing more than three files or recursive
alias showjobs="showq -u $USER"
alias canceljobs="mjobctl -c -w user=$USER"
alias colt="column -t -s$'\t'"

# Global exports
export scratchdir="/projects/b1042/sameer"
export gitprojectdir="/projects/b1049/sameer"

# Prevent git from using ssh-askpass
[ -n "$SSH_CONNECTION" ] && unset SSH_ASKPASS
export GIT_ASKPASS=

# project aliases
export famdir="${gitprojectdir}/LubbeLab/projects/family"
alias cdfam='cd ${famdir}'

# Load modules for vim and R to work
if [ -n "$MODULESHOME" ]; then
    module load vim/8.0.3.6
    module load tmux/2.3 
    module load R/3.4.4
fi
